[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_token_escrow = "BvyKgBXhcmTyfQ2EuZxR5hBsrrbEZZrbmZtftneCFoD5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/satya0111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
